# Rustfmt configuration for consistent code formatting
# Using only stable features to ensure CI/local parity

edition = "2021"
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Import formatting
reorder_imports = true
reorder_modules = true

# Code layout
remove_nested_parens = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true

# Width constraints
max_width = 100
chain_width = 80
single_line_if_else_max_width = 80
struct_lit_width = 40
struct_variant_width = 60
array_width = 80
fn_call_width = 80
attr_fn_like_width = 80

# Function and impl formatting
fn_params_layout = "Tall"

# Pattern formatting
match_arm_leading_pipes = "Never"